# Generated by Django 5.2.1 on 2025-06-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mrp', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('AMOUNT', 'Amount')], default='PERCENTAGE', max_length=50)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sr_no', models.CharField(blank=True, max_length=255, null=True)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, choices=[('PCS', 'Pieces'), ('KG', 'Kilograms'), ('LBS', 'Pounds'), ('LTR', 'Liters'), ('MTR', 'Meters')], max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('ptr', models.CharField(blank=True, max_length=255, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_inwarded', models.PositiveIntegerField(default=0)),
                ('buying_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_type', models.CharField(choices=[('GST', 'GST'), ('VAT', 'VAT'), ('CST', 'CST'), ('SERVICE_TAX', 'Service Tax')], default='GST', max_length=50)),
                ('stock_status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('LOW_STOCK', 'Low Stock'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], default='IN_STOCK', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('inward_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('WAREHOUSE TRANSFER', 'Warehouse Transfer'), ('RETURN', 'Return'), ('REPLACEMENT', 'Replacement')], default='PURCHASE', max_length=50)),
                ('additional_information', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('INWARD', 'INWARD'), ('OUTWARD', 'OUTWARD'), ('DAMAGED', 'DAMAGED'), ('LOST', 'LOST'), ('EXPIRED', 'EXPIRED'), ('RETURNED', 'RETURNED'), ('ADJUSTMENT', 'ADJUSTMENT'), ('WAREHOUSE TRANSFER', 'WAREHOUSE TRANSFER')], default='ACTIVE', max_length=50)),
                ('additional_information', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RackAndShlevesAndFloor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('rack', models.CharField(blank=True, max_length=255, null=True)),
                ('shelf', models.CharField(blank=True, max_length=255, null=True)),
                ('floor', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_information', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=255, null=True)),
                ('capacity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=255, null=True)),
                ('warehouse_type', models.CharField(blank=True, choices=[('OWNED', 'Owned'), ('RENTED', 'Rented'), ('SHARED', 'Shared')], max_length=255, null=True)),
                ('additional_information', models.JSONField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
