# Generated by Django 5.2.1 on 2025-06-02 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InventoryServices', '0001_initial'),
        ('OrderServices', '0001_initial'),
        ('ProductServices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory', to='ProductServices.products'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_inventory', to='OrderServices.purchaseorder'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_order_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_item_inventory', to='OrderServices.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_order_item_inwarded_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_item_inwarded_item_inventory', to='OrderServices.purchaseorderinwardedlog'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_inventory_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_inventory_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='inventory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_log', to='InventoryServices.inventory'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='po_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_inventory_log', to='OrderServices.purchaseorder'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='so_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so_inventory_log', to='OrderServices.salesorder'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='rack_shelf_floor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rack_shelf_floor_inventory_log', to='InventoryServices.rackandshlevesandfloor'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='rack_and_shelves_and_floor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rack_and_shelves_and_floor_inventory', to='InventoryServices.rackandshlevesandfloor'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_warehouse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_warehouse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_manager_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rackandshlevesandfloor',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_rack_and_shelves', to='InventoryServices.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inventory_log', to='InventoryServices.warehouse'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inventory', to='InventoryServices.warehouse'),
        ),
    ]
