# Generated by Django 5.2.1 on 2025-06-02 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InventoryServices', '0002_initial'),
        ('OrderServices', '0001_initial'),
        ('ProductServices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cancelled_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_cancelled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_domain_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='last_updated_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='recieved_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_received_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='returned_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_returned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='InventoryServices.warehouse'),
        ),
        migrations.AddField(
            model_name='purchaseorderinwardedlog',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderinwardedlog_domain_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderinwardedlog',
            name='inwarded_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderinwardedlog_inwarded_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderinwardedlog',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderinwardedlog_purchase_order', to='OrderServices.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='approved_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderitem_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='cancelled_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderitem_cancelled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderitem_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderitem_domain_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='po_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderitem_po', to='OrderServices.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderitem_product', to='ProductServices.products'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderitem_purchase_order', to='OrderServices.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='recieved_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderitem_received_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='updated_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderitem_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderiteminvardedlog',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderiteminvardedlog_domain_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderiteminvardedlog',
            name='inwarded_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderiteminvardedlog_inwarded_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderiteminvardedlog',
            name='purchase_order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderiteminvardedlog_purchase_order_item', to='OrderServices.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='purchaseorderlogs',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderlogs_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderlogs',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderlogs_domain_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderlogs',
            name='po_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderlogs_po', to='OrderServices.purchaseorder'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='approved_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='cancelled_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_cancelled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_domain_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='last_updated_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='recieved_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_received_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='returned_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_returned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='updated_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='approved_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorderitem_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='cancelled_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorderitem_cancelled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorderitem_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorderitem_domain_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesorderitem_product', to='ProductServices.products'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='purchase_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesorderitem_purchase_order', to='OrderServices.purchaseorder'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='shipped_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorderitem_shipped_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='so_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesorderitem_so', to='OrderServices.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='updated_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorderitem_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitemoutwardedlog',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorderitemoutwardedlog_domain_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitemoutwardedlog',
            name='outwarded_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorderitemoutwardedlog_outwarded_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitemoutwardedlog',
            name='so_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesorderitemoutwardedlog_so_item', to='OrderServices.salesorderitem'),
        ),
        migrations.AddField(
            model_name='salesorderlogs',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorderlogs_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderlogs',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorderlogs_domain_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderlogs',
            name='so_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesorderlogs_so', to='OrderServices.purchaseorder'),
        ),
        migrations.AddField(
            model_name='salesorderoutwardedlog',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorderoutwardedlog_domain_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderoutwardedlog',
            name='outwarded_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorderoutwardedlog_outwarded_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderoutwardedlog',
            name='so_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesorderoutwardedlog_so', to='OrderServices.salesorder'),
        ),
    ]
